/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/SignupScreen`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/proposal`; params?: Router.UnknownInputParams; } | { pathname: `/proposalDetail`; params?: Router.UnknownInputParams; } | { pathname: `/proposalsList`; params?: Router.UnknownInputParams; } | { pathname: `/signUp`; params?: Router.UnknownInputParams; } | { pathname: `/viewInvoice`; params?: Router.UnknownInputParams; } | { pathname: `/viewProposal`; params?: Router.UnknownInputParams; } | { pathname: `/invoice`; params?: Router.UnknownInputParams; } | { pathname: `/invoicesList`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/SignupScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/proposal`; params?: Router.UnknownOutputParams; } | { pathname: `/proposalDetail`; params?: Router.UnknownOutputParams; } | { pathname: `/proposalsList`; params?: Router.UnknownOutputParams; } | { pathname: `/signUp`; params?: Router.UnknownOutputParams; } | { pathname: `/viewInvoice`; params?: Router.UnknownOutputParams; } | { pathname: `/viewProposal`; params?: Router.UnknownOutputParams; } | { pathname: `/invoice`; params?: Router.UnknownOutputParams; } | { pathname: `/invoicesList`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/SignupScreen${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/proposal${`?${string}` | `#${string}` | ''}` | `/proposalDetail${`?${string}` | `#${string}` | ''}` | `/proposalsList${`?${string}` | `#${string}` | ''}` | `/signUp${`?${string}` | `#${string}` | ''}` | `/viewInvoice${`?${string}` | `#${string}` | ''}` | `/viewProposal${`?${string}` | `#${string}` | ''}` | `/invoice${`?${string}` | `#${string}` | ''}` | `/invoicesList${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/SignupScreen`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/proposal`; params?: Router.UnknownInputParams; } | { pathname: `/proposalDetail`; params?: Router.UnknownInputParams; } | { pathname: `/proposalsList`; params?: Router.UnknownInputParams; } | { pathname: `/signUp`; params?: Router.UnknownInputParams; } | { pathname: `/viewInvoice`; params?: Router.UnknownInputParams; } | { pathname: `/viewProposal`; params?: Router.UnknownInputParams; } | { pathname: `/invoice`; params?: Router.UnknownInputParams; } | { pathname: `/invoicesList`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
